name: Deploy to GitHub Pages via angular-cli-ghpages

on: [push]

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Use Node.js 10.x
              uses: actions/setup-node@v1
              with:
                  node-version: 10.x

            - name: Prepare
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
                  npm install
            - name: Deploy
              run: |
                  npm run deploy-ci-gh
