name: Prettier
on: [push]

jobs:
    build:
        name: Prettier
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout
                uses: actions/checkout@v2.5.0

            -   name: NPM or Yarn install with caching
                uses: bahmutov/npm-install@v1.6.0

            -   name: Prettify code
                uses: creyD/prettier_action@v4.2
                    with:
                        # This part is also where you can pass other options, for example:
                        prettier_options: --write **/*.{js,md}
