name: Sync
on:
    push:
        branches:
            - master

jobs:
    sync-branches:
        runs-on: ubuntu-latest
        name: Syncing branches
        steps:
            - name: Checkout
              uses: actions/checkout@v2.5.0
            - name: Set up Node
              uses: actions/setup-node@v3.5.1
              with:
                  node-version: 16
            - name: Opening pull request
              id: pull
              uses: tretuna/sync-branches@1.4.0
              with:
                  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
                  FROM_BRANCH: "master"
                  TO_BRANCH: "develop"
